django/twitter/timeline/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeTimelineView.as_view(), name='home'),
    url(r'^timeline/$', views.HomeTimelineView.as_view(), name='home_timeline'),
    url(r'^get_timeline/$', views.get_timeline, name='get_timeline'),
)

django/twitter/twitter/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'twitter.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^twitter/', include('timeline.urls', namespace='timeline')),
)

django/twitter/timeline/models.py
from django.db import models

# Create your models here


class TwitterUser(models.Model):
    user_id = models.CharField('User ID', max_length=40)
    username = models.CharField('User Name', max_length=100)
    is_following = models.BooleanField('Is following', default=False)
    is_follower = models.BooleanField('Is follower', default=False)
    description = models.TextField(null=True)

    def __unicode__(self):
        return self.username


class Tweet(models.Model):
    tid = models.CharField('Tweet ID', max_length=40)
    status = models.CharField('Status', max_length=140)
    author = models.ForeignKey(TwitterUser, verbose_name='Author')
    created_date = models.DateTimeField('Created Date', 'created date', null=True, blank=True)
    created_date_str = models.CharField(max_length=100)
    retweet_count = models.IntegerField()
    favourite_count = models.IntegerField()

    def __unicode__(self):
        return "Text = " + unicode(self.status)

class TweetStream(models.Model):
    tid = models.CharField('Tweet ID', max_length=40)
    status = models.CharField('Status', max_length=140)
    author = models.ForeignKey(TwitterUser, verbose_name='Author')
    created_date = models.DateTimeField('Created Date', 'created date', null=True, blank=True)
    created_date_str = models.CharField(max_length=100)
    retweet_count = models.IntegerField()
    favourite_count = models.IntegerField()

    def __unicode__(self):
        return "Text = " + unicode(self.status)

django/twitter/timeline/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from models import Tweet, TwitterUser
from django.contrib.auth.decorators import login_required
import twitter_api
import json

# Create your views here.


class HomeTimelineView(generic.ListView):
    model = Tweet
    template_name = 'tl/blog.html'
    context_object_name = 'tweets'
    paginate_by = 10
    def get_queryset(self):
        return Tweet.objects.order_by('-tid')


@login_required
def get_timeline(request):
    tweets = twitter_api.my_timeline()
    new_tweet_count = 0
    for tweet in tweets:
        try:
            Tweet.objects.get(tid=tweet.tid)
        except Tweet.DoesNotExist:
            user_existed = TwitterUser.objects.filter(user_id=tweet.author.user_id).exists()
            if not user_existed:
                tweet.author.save()
            twitter_user = TwitterUser.objects.get(user_id=tweet.author.user_id)
            tweet.author = twitter_user
            tweet.save()
            new_tweet_count += 1

    return HttpResponse(json.dumps({'count': new_tweet_count}), content_type="application/json")

django/twitter/timeline/templates/tl/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

django/twitter/timeline/templates/tl/blog.html
<!DOCTYPE html>
<!-- saved from url=(0039)http://getbootstrap.com/examples/blog/# -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/blog/blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="scripts/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style type="text/css"></style><style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
    .en-markup-crop-options {
        top: 18px !important;
        left: 50% !important;
        margin-left: -100px !important;
        width: 200px !important;
        border: 2px rgba(255,255,255,.38) solid !important;
        border-radius: 4px !important;
    }

    .en-markup-crop-options div div:first-of-type {
        margin-left: 0px !important;
    }
    </style></head>

<body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="#">Home Timeline</a>
          <a class="blog-nav-item" href="#">Connections</a>
          <a class="blog-nav-item" href="#">Streaming</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">The Twitter APIs Demo</h1>
        <p class="lead blog-description">Showcase Twitter REST & Streaming APIs</p>
      </div>

      <div class="row">
        <h5>@arcobaleno87 timeline</h5>
        <div class="col-sm-8 blog-main">
            {% if tweets %}

                {% for tweet in tweets %}
                <div class="blog-post">
                    <h3 class="twitter-status">{{ tweet.status }}</h3>
                    <p class="blog-post-meta">{{ tweet.created_date }} by <a href="#">{{ tweet.author.username }}</a></p>
                </div><!-- /.blog-post -->
                {% endfor %}

            {% endif %}

          <nav>
              {% if is_paginated %}
                <ul class="pagination pager">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <li><a href="{% url 'timeline:home_timeline' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <li><a href="{% url 'timeline:home_timeline' %}?page={{ page_obj.next_page_number }}">next</a></li>
                        {% endif %}
                    </span>
                </ul>
              {% endif %}
          </nav>

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="script/jquery.min.js"></script>
    <script src="script/bootstrap.min.js"></script>
    <script src="script/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="script/ie10-viewport-bug-workaround.js"></script>


<div id="global-zeroclipboard-html-bridge" class="global-zeroclipboard-container" style="position: absolute; left: 0px; top: -9999px; width: 15px; height: 15px; z-index: 999999999;" title="" data-original-title="Copy to clipboard">      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="global-zeroclipboard-flash-bridge" width="100%" height="100%">         <param name="movie" value="/assets/flash/ZeroClipboard.swf?noCache=1421739593665">         <param name="allowScriptAccess" value="sameDomain">         <param name="scale" value="exactfit">         <param name="loop" value="false">         <param name="menu" value="false">         <param name="quality" value="best">         <param name="bgcolor" value="#ffffff">         <param name="wmode" value="transparent">         <param name="flashvars" value="trustedOrigins=getbootstrap.com%2C%2F%2Fgetbootstrap.com%2Chttp%3A%2F%2Fgetbootstrap.com">         <embed src="/assets/flash/ZeroClipboard.swf?noCache=1421739593665" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="100%" height="100%" name="global-zeroclipboard-flash-bridge" allowscriptaccess="sameDomain" allowfullscreen="false" type="application/x-shockwave-flash" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="trustedOrigins=getbootstrap.com%2C%2F%2Fgetbootstrap.com%2Chttp%3A%2F%2Fgetbootstrap.com" scale="exactfit">                </object></div>
</body></html>