django/django_samples/blog/urls.py
from django.conf.urls import patterns, url
from blog import views
import django.contrib.auth.views

urlpatterns = patterns(
    '',
    url(r'^$', views.MainView.as_view(), name='main'),
    url(r'^post/(?P<pk>\d+)$', views.post_view, name='post'),
    url(r'^post/(?P<post_id>\d+)/post_comment$', views.post_comment, name='post-comment'),
    url(r'^auth/login$', views.blog_login, name='login'),
    url(r'^auth/logout$', views.blog_logout, name='logout'),
    url(r'^auth/login$', django.contrib.auth.views.login, name='django.contrib.auth.views.login'),
    url(r'^auth/logout$', django.contrib.auth.views.logout, name='django.contrib.auth.views.logout'),
)

django/django_samples/rest_demo/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

django/django_samples/sample_home/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'home.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^todo/', include('todo.urls', namespace='todo')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^rest/', include('rest_demo.urls', namespace='rest_demo')),
)

django/django_samples/todo/urls.py
from django.conf.urls import patterns, url
from todo import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.create_task, name='create'),
)

django/django_samples/blog/models.py
from django.db import models

# Create your models here.
from django.forms import ModelForm


class Post(models.Model):
    title = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    author = models.CharField(max_length=80)
    message = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return self.message


# need to find a way to specify field names in the form
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ['post']

django/django_samples/home/models.py
from django.db import models

# Create your models here.

django/django_samples/rest_demo/models.py
from django.db import models

# Create your models here.

django/django_samples/todo/models.py
from django.db import models

# Create your models here.


class DateTime(models.Model):
    datetime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return unicode(self.datetime)


class Item(models.Model):
    name = models.CharField(max_length=100)
    created = models.ForeignKey(DateTime)
    priority = models.IntegerField(default=0)
    difficulty = models.IntegerField(default=0)
    done = models.BooleanField(default=False)

django/django_samples/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from models import Post, Comment, CommentForm
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.


class MainView(generic.ListView):
    """Main blog post listing"""

    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'

    paginate_by = 2

    def get_queryset(self):
        # get all posts order by create date, from newest to oldest
        posts = Post.objects.all().order_by("-created")
        return posts

        # paging posts, 2 posts in each page
        #paginator = Paginator(posts, 2)

        #try:
        #    page = int(request.GET.get('page', '1'))
        #except ValueError:
        #    page = 1

        #try:
        #    posts = paginator.page(page)
        #except (InvalidPage, EmptyPage):
        #    posts = paginator.page(paginator.num_pages)

    # return render(request, 'blog/index.html', {
    #    'posts': posts
    # })


#class PostView(generic.DetailView):
#    model = Post
#    context_object_name = 'post'
#    template_name = 'blog/post.html'

def post_view(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post.html', {
        'post': post,
        'cm_form': CommentForm()
    })


@login_required
def post_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    cm_author = request.POST['comment-author']
    cm_message = request.POST['comment-message']
    if not cm_author or not cm_message:
        return render(request, 'blog/post.html', {
            'post': post,
        })

    comment = Comment.objects.create(author=cm_author, message=cm_message, post=post)
    return HttpResponseRedirect(reverse('blog:post', args=(post_id,)))




def blog_login(request):
    username = request.POST['username']
    password = request.POST['password']

    redirect_to = request.REQUEST.get('return_url', '')

    user = authenticate(username=username, password=password)
    if user is not None:
        #if user.is_active:
        login(request, user)
        if redirect_to:
            return HttpResponseRedirect(redirect_to)
        else:
            return HttpResponseRedirect(reverse('blog:main'))
        #else:
    else:
        return HttpResponseRedirect(reverse('blog:main'))


def blog_logout(request):
    redirect_to = request.REQUEST.get('return_url', reverse('blog:main'))
    logout(request)
    return HttpResponseRedirect(redirect_to)

django/django_samples/home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

django/django_samples/rest_demo/views.py
from django.shortcuts import render

# Create your views here.

django/django_samples/todo/views.py
from django.shortcuts import render
from django.views import generic
from models import Item, DateTime
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'todo/index.html'
    context_object_name = 'todo_list'

    def get_queryset(self):
        return Item.objects.all()


def create_task(request):
    task_text = request.POST['task']
    print(task_text)
    if not task_text:
        return render(request, 'todo/index.html', {
            'error_message': "You didn't select a choice.",
            'todo_list': Item.objects.all()
        })

    dtime = DateTime.objects.create()
    task = Item.objects.create(name=task_text, created=dtime)
    return HttpResponseRedirect(reverse('todo:index'))

django/django_samples/blog/templates/blog/bbase.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}MyBlog{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/blog/blog.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="scripts/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css"></style><style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
        .en-markup-crop-options {
            top: 18px !important;
            left: 50% !important;
            margin-left: -100px !important;
            width: 200px !important;
            border: 2px rgba(255,255,255,.38) solid !important;
            border-radius: 4px !important;
        }

        .en-markup-crop-options div div:first-of-type {
            margin-left: 0px !important;
        }

        .blog-masthead .blog-nav {
            float: left;

        }

        .blog-masthead .user-info {
            float: right;

        }

        .login-form .login-form-input {
            border: 1px solid;
            width: 100px;
            padding: 2px;
        }

        .user-info {
            padding: 10px 0;
        }

        .user-info .logged-user-info, .user-info .logged-user-info a {
            color: #ffffff;
        }

        .login-form label {
            color: white;
        }
    </style>
</head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    
    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'blog:main' %}">Home</a>
          <a class="blog-nav-item" href="#">New features</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="#">New hires</a>
          <a class="blog-nav-item" href="#">About</a>
          {% if user.is_staff %}
            <a class="blog-nav-item" href="{% url 'admin:index' %}">Admin</a>
            <a class="blog-nav-item" href="{% url 'admin:blog_post_add' %}">Add post</a>
          {% endif %}
        </nav>
        <div class="user-info">
            <!--
            {% if user.is_authenticated %}
                <span class="logged-user-info">Welcome <strong><a href="#">{{ user.username }}</a></strong>&nbsp;
                <a href="{% url 'blog:django.contrib.auth.views.logout' %}?next={{request.path}}">logout</a>
                </span>
            {% else %}
                <form class="login-form" id="login-form" method="post" action="{% url 'blog:django.contrib.auth.views.login' %}?next={{request.path}}">
                    {% csrf_token %}
                    <label for="login-username">Username</label>&nbsp;
                    <input type="text" id="login-username" name="username" class="login-form-input" />
                    &nbsp;
                    <label for="login-password">Password</label>&nbsp;
                    <input type="password" id="login-password" name="password" class="login-form-input" />&nbsp;
                    <input type="submit" id="login-submit" value="Login" />
                </form>
            {% endif  %} -->

            {% if user.is_authenticated %}
                <span class="logged-user-info">Welcome <strong><a href="#">{{ user.username }}</a></strong>&nbsp;
                <a href="{% url 'blog:logout' %}?return_url={{request.path}}">logout</a>
                </span>
            {% else %}
                <form class="login-form" id="login-form" method="post" action="{% url 'blog:login' %}?return_url={{request.path}}">
                    {% csrf_token %}
                    <label for="login-username">Username</label>&nbsp;
                    <input type="text" id="login-username" name="username" class="login-form-input" />
                    &nbsp;
                    <label for="login-password">Password</label>&nbsp;
                    <input type="password" id="login-password" name="password" class="login-form-input" />&nbsp;
                    <input type="submit" id="login-submit" value="Login" />
                </form>
            {% endif  %}
        </div>
      </div>
    </div>
    
    <div id="container" class="container">
        <div class="blog-header">
            <h1 class="blog-title">The Bootstrap Blog</h1>
            <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
        </div>
        <div id="content">
            <div class="row">
                <div class="col-sm-8 blog-main">
                    {% block main-content %}{% endblock %}
                </div>

                <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
                    <div class="sidebar-module sidebar-module-inset">
                        <h4>About</h4>
                        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                    </div>
                    <div class="sidebar-module">
                        <h4>Archives</h4>
                        <ol class="list-unstyled">
                          <li><a href="#">March 2014</a></li>
                          <li><a href="#">February 2014</a></li>
                          <li><a href="#">January 2014</a></li>
                          <li><a href="#">December 2013</a></li>
                          <li><a href="#">November 2013</a></li>
                          <li><a href="#">October 2013</a></li>
                          <li><a href="#">September 2013</a></li>
                          <li><a href="#">August 2013</a></li>
                          <li><a href="#">July 2013</a></li>
                          <li><a href="#">June 2013</a></li>
                          <li><a href="#">May 2013</a></li>
                          <li><a href="#">April 2013</a></li>
                        </ol>
                    </div>
                    <div class="sidebar-module">
                        <h4>Elsewhere</h4>
                        <ol class="list-unstyled">
                          <li><a href="#">GitHub</a></li>
                          <li><a href="#">Twitter</a></li>
                          <li><a href="#">Facebook</a></li>
                        </ol>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="scripts/jquery.min.js"></script>
    <script src="scripts/bootstrap.min.js"></script>
    <script src="scripts/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="scripts/ie10-viewport-bug-workaround.js"></script>


    <div id="global-zeroclipboard-html-bridge" class="global-zeroclipboard-container" style="position: absolute; left: 0px; top: -9999px; width: 15px; height: 15px; z-index: 999999999;" title="" data-original-title="Copy to clipboard">      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="global-zeroclipboard-flash-bridge" width="100%" height="100%">         <param name="movie" value="/assets/flash/ZeroClipboard.swf?noCache=1421739593665">         <param name="allowScriptAccess" value="sameDomain">         <param name="scale" value="exactfit">         <param name="loop" value="false">         <param name="menu" value="false">         <param name="quality" value="best">         <param name="bgcolor" value="#ffffff">         <param name="wmode" value="transparent">         <param name="flashvars" value="trustedOrigins=getbootstrap.com%2C%2F%2Fgetbootstrap.com%2Chttp%3A%2F%2Fgetbootstrap.com">         <embed src="/assets/flash/ZeroClipboard.swf?noCache=1421739593665" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="100%" height="100%" name="global-zeroclipboard-flash-bridge" allowscriptaccess="sameDomain" allowfullscreen="false" type="application/x-shockwave-flash" wmode="transparent" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="trustedOrigins=getbootstrap.com%2C%2F%2Fgetbootstrap.com%2Chttp%3A%2F%2Fgetbootstrap.com" scale="exactfit">                </object></div>

</body>
</html>

django/django_samples/blog/templates/blog/index.html
{% extends "blog/bbase.html" %}

{% block main-content %}
    {% if posts %}
        {% for post in posts %}
            <div class="blog-post">
                <h4 class="blog-post-title"><a href="{% url 'blog:post' post.id %}">{{ post.title }}</a></h4>
                <p class="blog-post-meta">{{ post.created }} by <a href="#">Mark</a></p>
                <p>{{ post.body|linebreaks }}</p>
            </div><!-- /.blog-post -->
        {% endfor %}
    {% endif %}

    {% if is_paginated %}
        <nav>
            <ul class="pager">
                {% if page_obj.has_previous %}
                    <li><a href= "?page={{ page_obj.previous_page_number }}">newer &lt;&lt; </a></li>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}"> &gt;&gt; older</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif  %}

{% endblock %}

django/django_samples/blog/templates/blog/post.html
{% extends "blog/bbase.html" %}

{% block main-content %}
    <div class="blog-post">
        <h4 class="blog-post-title">{{ post.title }}</h4>
        <p class="blog-post-meta">{{ post.created }} by <a href="#">Mark</a></p>
        <p>{{ post.body|linebreaks }}</p>
    </div><!-- /.blog-post -->
    <div class="comments">
        <h3>Comments</h3>
        <div class="post-comment">
            <!--form class="post-comment-form" id="post-comment-form" method="POST" action="{% url 'blog:post-comment' post.id %}">
                {% csrf_token %}
                <label class="comment-label">Your name</label>&nbsp;
                <input type="text" id="comment-author" name="comment-author" required="true" />
                <br/>
                <label class="comment-label">Message</label>&nbsp;
                <textarea cols="40" rows="5" id="comment-message" name="comment-message" required="true"></textarea>
                <button id="submit-comment">Submit</button>
            </form-->
            <form id="post-comment-form" method="post" action="{% url 'blog:post-comment' post.id %}">
                {% csrf_token %}
                Name: {{ cm_form.author }}
                <p>
                Message: {{ cm_form.message | linebreaks }}<p>
                <button id="submit-comment">Submit</button>
            </form>
        </div>

        <div class="existing-comments">
            {% if post.comment_set.all.count > 0 %}
                {% for comment in post.comment_set.all %}
                    <div class="comment-content">
                        <strong>{{ comment.author }}</strong> says<br/>
                        <span style="color: gray; font-size: 8px;">{{ comment.created }}</span><br/>
                        <span>{{ comment.message }}</span>
                    </div>
                {% endfor %}
            {% else %}
                <span>No comment yet</span>
            {% endif  %}
        </div>
    </div>
{% endblock %}

django/django_samples/home/templates/home/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>Welcome to Django samples home page</p>
<p>Available Applications</p>
<ul>
    <li><a href="{% url 'todo:index' %}">Todo App</a></li>
    <li><a href="{% url 'blog:main' %}">Blog App</a></li>
</ul>
</body>
</html>

django/django_samples/todo/templates/todo/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    {% if error_message %} <p><strong style="color:red">{{ error_message }}</strong></p> {% endif %}
    <div class="todo-list-container">
        <h3>Todo</h3>
        {% if todo_list %}
            {% for item in todo_list %}
                <div class="todo-item">
                    <span>{{ item.name }}</span>

                </div>
            {% endfor %}
        {% else %}
            <span>No TODO - You're completely free :)</span>
        {% endif %}

    </div>
    <div>
        <form action="{% url 'todo:create' %}" method="post">
            {% csrf_token %}
            <label for="new-task">Task</label>
            <input type="text" name="task" id="new-task" />
            <input type="submit" id="create-task" value="Create" />
        </form>
    </div>
</body>
</html>